### PR TITLE
Replace broken maven link with PrisonDataEditor

### PR DESCRIPTION
**Pull request by Perksey**

### CODE REVIEW

**Comment by fdatoo** [comment]
The mc-prison.tech website is primarily for Prison v3.0, and v3 has a different storage system that won't work with Prison Data Editor. It doesn't seem to be the place to put this link.

**Comment by Perksey** [comment]
Alright. Might want to fix those broken links though! ;)

**Comment by fdatoo** [comment]
Yes, we used to have our own CI and maven repositories, but we've run out of funds to keep them up (due to lack of donations). I'll probably be replacing the CI with Travis-CI and the Maven repository with a wagon-ftp setup.

**Comment by Perksey** [comment]
Cool. If you need it, I can host Javadoc, seeing as that link is broken too.

**Comment by fdatoo** [comment]
The link is broken because we haven't finalized the core yet, so the docs have yet to be generated and uploaded.

Thanks anyways :)

**Comment by Perksey** [comment]
Also looking at your save system, I recommend using google Gson as it's built into bukkit

**Comment by fdatoo** [comment]
The original prototypes of the v3.0 save system did use GSON. However, I constantly ran into problems with GSON and decided to create something completely suited to Prison.

**Pull request closed without merging**
